### ISSUE TITLE
crc32 is incomplete.

### ISSUE THREAD

**Issue by slicer4ever** [Chlumsky/artery-font-format#1]
the crc32.h never does the final ^0xFFFFFFFF to checksum when all the data has been serialized.

**Comment by Chlumsky** [comment]
I guess you are right, but it doesn't matter. It still serves its purpose as CRC perfectly fine and since the same "bug" is present in both serialization and deserialization, it cancels out. Fixing this would break existing files.

**Comment by slicer4ever** [comment]
Fair enough, just figured I'd give you a heads up.
