### ISSUE TITLE
Error when reading example font

### ISSUE THREAD

**Issue by Jairard** [Chlumsky/artery-font-format#4]
Hi,

I am trying to read the [example font](https://github.com/Chlumsky/artery-font-format/blob/master/example.arfont) as a test for the library, but `artery_font::read` returns `false`. Am I doing something wrong or is the file outdated ?

```cpp
#include <cstdio>
#include <cstdlib>
#include <iostream>

#include <std-artery-font.h>
#include <stdio-serialization.h>

int main() {
  FILE *const font_file = fopen("example.arfont", "r");
  if (font_file == nullptr) {
    std::cerr << "couldn't open font file" << std::endl;
    return EXIT_FAILURE;
  }

  artery_font::StdArteryFont<float> font;
  if (!artery_font::read(font, font_file)) {
    std::cerr << "couldn't read artery font" << std::endl;
    return EXIT_FAILURE;
  }

  return fclose(font_file) == 0;
}
```

**Comment by Chlumsky** [comment]
With `fopen("example.arfont", "r")` you open the binary file in text mode, which corrupts the data. You have to use `"rb"` instead.

**Comment by Jairard** [comment]
You're right, I feel dumb now 🤦‍♂️
