### ISSUE TITLE
No release tag

### ISSUE THREAD

**Issue by Jairard** [Chlumsky/artery-font-format#5]
Hi,

as an effort to upload a package for this library into [conan center](https://github.com/conan-io/conan-center-index/pull/6705), I noticed from the code that the version of this lib is 1.0, but there is no tag. This is not a big problem since there is a procedure for libraries without official versions, but I thought that it would be nice to have the tag for this purpose as long as others.

**N.B:** since it is a header-only library, the integration to conan packaging won't require any file addition in this repo.

**Comment by Chlumsky** [comment]
Alright, I have added a tag.
