### ISSUE TITLE
Cant load arfonts generated by latest win64 release of msdf-atlas-gen

### ISSUE THREAD

**Issue by nickk-dv** [Chlumsky/artery-font-format#6]
example.arfont from version 1.0.1 works fine.
when i generate arfont with msdf-atlas-gen.exe arfonts always fail to load.
im not sure if arfont format is designed to be widely used or its just internal thing?

using png + json given by msdf-atlas-gen.exe is the only other option to get font data?

**Comment by HifiExperiments** [comment]
I'm having the same issue.  specifically, the checksum check at the end of decode fails.  my generation command looks like `msdf-atlas-gen.exe -font Roboto.ttf -type mtsdf -fontname Roboto -format png -arfont Roboto.arfont`

do you remember what the solution was here or did you just switch to a different format?

**Comment by nickk-dv** [comment]
> I'm having the same issue. specifically, the checksum check at the end of decode fails. my generation command looks like `msdf-atlas-gen.exe -font Roboto.ttf -type mtsdf -fontname Roboto -format png -arfont Roboto.arfont`
> 
> do you remember what the solution was here or did you just switch to a different format?

It was a long time ago, but I switched to using json as temporary font data format, instead of arfont format.
Command to generate msdf font produces `font_data (.json)` and `atlas (.png)`
In my project (game engine) I read that json and store it in other format (.yaml in my case), getting glyph data and font atlas as the result.

```c++
// here's the example command I used:
std::string command = "dependencies\\msdf-atlas-gen.exe -font " + path + " -type msdf -pots -format png -imageout " + atlasPath + " -json " + jsonPath + " -scanline\n";
int result = system(command.c_str());
```

**Comment by Chlumsky** [comment]
For me the arfont files work so I'm not sure what the problem could be, especially if you are able to load the example file. One thing that comes to mind is that you can pick between single and double floating-point precision when you save and load the file, and this choice has to match, otherwise it will just fail without providing the reason. The atlas generator uses single-precision (`float`), so make sure you use that as the `REAL` template argument.

**Comment by HifiExperiments** [comment]
for me, the problem ended up entirely being the checksum.  I have no idea why it would be failing, could totally be something wrong on my end.  even with the example font, it would actually still fail intermittently.

surely bad practice on my end, but I actually just ended up patching it to comment the checksum check out and now it works perfectly: https://github.com/overte-org/overte/pull/937/files#diff-80d86d4416bd497a5aa3edba9f2dbf03ebab2f955e4ac8dc3205bf594defe46bR35

I will keep investigating though.  thank you for all these awesome tools!

**Comment by Chlumsky** [comment]
Can you maybe provide a file where the checksum fails, so that I can look into it?

**Comment by HifiExperiments** [comment]
[Roboto.zip](https://github.com/Chlumsky/artery-font-format/files/15016028/Roboto.zip)

**Comment by Chlumsky** [comment]
For me, the file's checksum matches the expected value when loaded.

**Comment by HifiExperiments** [comment]
we use Qt for reading the files so it's possible something is going wrong with the data there too.  if you're curious, here's where we call decode: https://github.com/overte-org/overte/pull/937/files#diff-0ca8e5d6c1e76bc5214416e9ac088201ac9d723a6f4ecbd186463286d0e4a48fR119

but it's not a big deal, we're just excited to have nicer fonts 😃
