### ISSUE TITLE
Any plan to release latest version?

### ISSUE THREAD

**Issue by toge** [Chlumsky/artery-font-format#7]
I found `distanceRangeMiddle` field has been added on [latest commit](https://github.com/Chlumsky/artery-font-format/commit/888674220216d1d326c6f29cf89165b545279c1f).

It seems to be necessary for msdf-atlas-gen 1.3.0.

Do you have any plan to release latest version?

**Comment by Chlumsky** [comment]
Done.

**Comment by toge** [comment]
@Chlumsky 
Thanks!
